### ISSUE TITLE
component inside a group alignment issue

### ISSUE THREAD

**Issue by dfelinto** [martijnberger/pyslapi#5]
I found a bug with a particular file. I have a component inside a group, and the resulting alignment in Blender is wrong.

(file: http://www.dalaifelinto.com/ftp/tmp/bug-cortina.skp )

SketchUp side view:
![screen shot 2015-08-13 at 12 46 31 pm](https://cloud.githubusercontent.com/assets/843498/9254364/7ae48df4-41b9-11e5-9a30-35b89a9a615f.png)

Blender side view:
![screen shot 2015-08-13 at 12 46 49 pm](https://cloud.githubusercontent.com/assets/843498/9254365/7ae9e4de-41b9-11e5-908e-e2294e31ad37.png)

**Comment by martijnberger** [comment]
The file link does not work for me..

**Comment by dfelinto** [comment]
Fixed.

**Comment by mirlip** [comment]
@dfelinto do you mean you fixed the bug or you fixed the link? because for me, the bug still show up with the file you linked. Anyway, nice 0.13 update martin :)

**Comment by dfelinto** [comment]
I fixed the link only, sorry

**Comment by martijnberger** [comment]
I cannot reproduce. What versions did you use ?

**Comment by andreimd87** [comment]
same bug here.  like exploding my project :(
![2](https://cloud.githubusercontent.com/assets/19931241/18382733/f33cff32-768a-11e6-9e2b-6ece0dfeb62d.JPG)
![1](https://cloud.githubusercontent.com/assets/19931241/18382734/f3542c16-768a-11e6-90e0-d02d4bf8c50d.jpg)

**Comment by andreimd87** [comment]
found a temp solution. save project in skp ver.4 or 5 then import in blender. :) but i still hope this bug will be fixed.

**Comment by andreimd87** [comment]
i found that bug is coming from names of groups. i use this kind of name in my sketchup  projects "nu|a242,xy" its some specifications for each detail.

**Comment by andreimd87** [comment]
looks like it does not accept any kind of names. that's why we need to save in an oldiest skp wich removes all group or component names.

**Comment by andreimd87** [comment]
the last config that i remained at is blender 2.76b win64 with skp importer v 0.13 and sketchup 2014. now i dont see any bug i guess......
